version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports: 
      - "5000:5000"

  frontend:
    build:
      context: ./extension
    ports: 
      - "3000:3000"
    depends_on:
      - backend
